package com.xl.springclouddemoservice.dao;

import com.xl.springclouddemoservice.entity.School;

public interface SchoolDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Tue Sep 24 15:43:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Tue Sep 24 15:43:48 CST 2019
     */
    int insert(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Tue Sep 24 15:43:48 CST 2019
     */
    int insertSelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Tue Sep 24 15:43:48 CST 2019
     */
    School selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Tue Sep 24 15:43:48 CST 2019
     */
    int updateByPrimaryKeySelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Tue Sep 24 15:43:48 CST 2019
     */
    int updateByPrimaryKey(School record);
}