server:
  port: 8773



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALqXe1ncw3rJujiPlLZOrs4NawCca77oAl9y3A5OtAN9InIGPO1+PuEOu1LlSlVNlVIg5UHvWGAaWg1ZUwmZxtcCAwEAAQ==
spring:
  application:
    name: springclouddemoservice
  datasource:
    url: jdbc:mysql://localhost:3306/tx-manager?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: UKQ9ohlOw0VDS4Br0eSuMpohUZt3h+8tujfL+KCyc5UFYFRr1dMquRDCdrWyVQb2ERTUhOdtbHFaqczRYolI2A==
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 2
      minIdle: 10
      maxWait: 60000
      maxActive: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: true
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      web-stat-filter:
        session-stat-enable: flase
      filter:
        config:
          enabled: true
      connect-properties:
        config.decrypt: true
        config.decrypt.key: ${public-key}
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
mybatis:
  type-aliases-package: com.xl.springclouddemoservice.entity
  mapper-locations: classpath:mybatis/mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

